src/Maetsilor/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Maetsilor.Data;
using Maetsilor.Models.ForumViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Maetsilor.Controllers
{
    [Authorize(Roles = "Utilisateur,Moderateur,Administrateur")]
    public class ForumController : Controller
    {
        private ApplicationDbContext _context = null;
        public ForumController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: Forum
        public ActionResult Index()
        {
            List<Sujet> ls = new List<Sujet>();
            foreach(Sujet s in _context.Sujets)
            {
                ls.Add(s);
            }
            return View(ls);
        }

        // GET: Forum/Details/5
        public ActionResult Details(int id)
        {
            Sujet s = _context.Sujets.FirstOrDefault(su => su.ID == id);
            if (s.Messages == null) s.Messages = new List<Message>();
            return View(s);
        }

        // GET: Forum/Create
        public ActionResult Create()
        {
            return View("Create");
        }

        // POST: Forum/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                Sujet sujet = new Sujet();
                TryUpdateModelAsync(sujet);
                sujet.NbReponse = 0;
                sujet.DateCreation = DateTime.Now;
                sujet.Auteur = HttpContext.User.Identity.Name.ToString(); 
                _context.Sujets.Add(sujet);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Home");
            }
        }

        // GET: Forum/Edit/5
        public ActionResult Edit(int id)
        {
            Sujet s = _context.Sujets.FirstOrDefault(su=>su.ID == id);
            return View(s);
        }

        // POST: Forum/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                Sujet sujet = _context.Sujets.FirstOrDefault(su => su.ID == id);
                TryUpdateModelAsync(sujet);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Forum/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                Sujet s = _context.Sujets.FirstOrDefault(su => su.ID == id);
                _context.Sujets.Remove(s);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // POST: Forum/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                Sujet s = _context.Sujets.FirstOrDefault(su => su.ID == id);
                _context.Sujets.Remove(s);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        

        // POST: Forum/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateMessage(int id, IFormCollection collection)
        {
            try
            {
                Sujet s = _context.Sujets.FirstOrDefault(su => su.ID == id);
                Message m = new Message() { Auteur = HttpContext.User.Identity.Name.ToString(), Texte = "TEST" + s.Messages.Count() };
                s.Messages.Add(m);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

src/Maetsilor/Controllers/MatchMakingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Maetsilor.Data;
using Maetsilor.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Maetsilor.Models.MatchMakingViewModel;
using Microsoft.EntityFrameworkCore;

namespace Maetsilor.Controllers
{
    public class MatchMakingController : Controller
    {
        private ApplicationDbContext _context = null;
        private readonly UserManager<ApplicationUser> _userManager;

        public MatchMakingController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        // GET: MatchMaking
        public ActionResult Index()
        {
            ApplicationUser user = _context.Users.First(u => u.UserName == HttpContext.User.Identity.Name);
            List<Group> groups = _context.Groups.ToList();
            List<int> userGroups = new List<int>();
            foreach(Group g in groups)
            {
                if(_context.UserGroups.Any(ug => ug.GroupID == g.ID && ug.UserID == user.Id))
                {
                    userGroups.Add(g.ID);
                }
            }
            ViewData["UserGroups"] = userGroups;
            return View(groups);
        }

        // GET: MatchMaking
        public ActionResult IndexUserGroups()
        {
            ApplicationUser user = _context.Users.First(u => u.UserName == HttpContext.User.Identity.Name);

            if (user == null)
            {
                return View("Error");
            }
            List<Group> groups = new List<Group>();
            foreach (UserGroup ug in _context.UserGroups)
            {
                if (ug.UserID == user.Id)
                {
                    Group g = _context.Groups.FirstOrDefault(gr => gr.ID == ug.GroupID);
                    groups.Add(g);
                }
            }
            return View(groups);
        }

        // GET: MatchMaking/Details/5
        public ActionResult Details(int id)
        {
            Group g = _context.Groups.Where(gr => gr.ID == id).Single();
            return View(g);
        }

        // GET: MatchMaking/Create
        public ActionResult Create()
        {
            return View("Create");
        }

        // POST: MatchMaking/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                ApplicationUser user = _context.Users.First(u => u.UserName == HttpContext.User.Identity.Name);
                if (user == null)
                {
                    return View("Error");
                }
                Group g = new Group();
                TryUpdateModelAsync(g);
                g.MaitreDuJeu = user.UserName;
                g.ID = 0;
                g.Membres = new List<ApplicationUser>();
                g.Chat = new List<ChatMessage>();
                g.Membres.Add(user);
                _context.Add(g);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        // GET: MatchMaking/IndexMembre/5
        public ActionResult IndexMembre(int id)
        {
            Group g = _context.Groups.FirstOrDefault(gr => gr.ID == id);
            List<Membre> lm = new List<Membre>();
            foreach (UserGroup ug in _context.UserGroups)
            {
                if (ug.GroupID == g.ID && ug.IsMember)
                {
                    ApplicationUser user = _context.Users.FirstOrDefault(u => u.Id == ug.UserID);
                    Membre m = new Membre(user);
                    lm.Add(m);
                }
            }
            ViewData["GroupID"] = id;
            ViewData["GroupMaster"] = g.MaitreDuJeu;
            return View(lm);
        }
        // GET: MatchMaking/IndexDemandes
        public ActionResult IndexDemandes(int id)
        {
            Group g = _context.Groups.FirstOrDefault(gr => gr.ID == id);
            List<Membre> lm = new List<Membre>();
            foreach (UserGroup ug in _context.UserGroups)
            {
                if (ug.GroupID == g.ID && !ug.IsMember)
                {
                    ApplicationUser user = _context.Users.FirstOrDefault(u => u.Id == ug.UserID);
                    Membre m = new Membre(user);
                    lm.Add(m);
                }
            }
            ViewData["GroupID"] = id;
            ViewData["GroupMaster"] = g.MaitreDuJeu;
            return View(lm);
        }

        // GET: MatchMaking/Chat
        public ActionResult Chat(int id)
        {
            Group g = _context.Groups.FirstOrDefault(gr => gr.ID == id);
            List<ChatMessage> lm = new List<ChatMessage>();
            foreach (ChatMessage c in _context.ChatMessages.ToList())
            {
                if (c.GroupID == g.ID)
                {
                    lm.Add(c);
                }
            }
            ViewData["GroupID"] = id;
            ViewData["GroupMaster"] = g.MaitreDuJeu;
            return View(lm);
        }

        // GET: MatchMaking/ChatReply
        public ActionResult ChatReply(int id)
        {
            Group g = _context.Groups.FirstOrDefault(gr => gr.ID == id);
            ViewData["GroupID"] = id;
            return View();
        }

        // POST: MatchMaking/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChatReply(ChatMessage reply)
        {
            try
            {
                ApplicationUser user = _context.Users.First(u => u.UserName == HttpContext.User.Identity.Name);
                if (user == null)
                {
                    return View("Error");
                }
                ChatMessage m = new ChatMessage();

                m.Auteur = user.ToString();
                m.Date = DateTime.UtcNow;
                m.Message =  reply.Message;
                m.GroupID = reply.ID;
                _context.ChatMessages.Add(m);
                _context.SaveChanges();
                return RedirectToAction("Chat", new { id = reply.ID });
            }
            catch
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: MatchMaking/Edit/5
        public ActionResult Edit(int id)
        {
            Group g = _context.Groups.FirstOrDefault(gr => gr.ID == id);
            return View(g);
        }

        // POST: MatchMaking/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                Group g = _context.Groups.FirstOrDefault(gr => gr.ID == id);
                TryUpdateModelAsync(g);
                _context.SaveChanges();
                return RedirectToAction("Details", new { id = g.ID });
            }
            catch
            {
                return View();
            }
        }

        // GET: MatchMaking/Delete/5
        public ActionResult Delete(int id)
        {
            Group g = _context.Groups.FirstOrDefault(gr => gr.ID == id);
            return View(g);
        }

        // POST: MatchMaking/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {

                Group g = _context.Groups.Where(gr => gr.ID == id).Single();
                _context.Groups.Remove(g);
                _context.SaveChanges();
                return RedirectToAction("IndexUserGroups");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Join(int id, IFormCollection collection)
        {
            try
            {
                ApplicationUser user = _context.Users.First(u => u.UserName == HttpContext.User.Identity.Name);
                if (user == null)
                {
                    return View("Error");
                }
                Group g = _context.Groups.FirstOrDefault(gr => gr.ID == id);
                UserGroup ug = new UserGroup();
                ug.GroupID = g.ID;
                ug.UserID = user.Id;
                ug.IsMember = false;
                _context.Add(ug);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult KickMember(int id, string memberId)
        {
            try
            {
                UserGroup ug = _context.UserGroups.FirstOrDefault(u => u.GroupID == id && u.UserID == memberId);
                _context.Remove(ug);
                _context.SaveChanges();
                return RedirectToAction("IndexMembre", new { id = id });
            }
            catch
            {
                return RedirectToAction("Index", "Home");
            }
        }


        // GET: MatchMaking/IndexCalendrier
        public ActionResult IndexCalendrier(int id)
        {
            Group g = _context.Groups.FirstOrDefault(gr => gr.ID == id);
            ViewData["GroupID"] = id;
            ViewData["GroupMaster"] = g.MaitreDuJeu;
            List<Partie> lp = new List<Partie>();
            foreach (Partie p in _context.Parties)
            {
                if (p.GroupID == g.ID)
                {
                    lp.Add(p);
                }
            }
            return View(lp);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]

src/Maetsilor/Controllers/MembreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Maetsilor.Data;
using Maetsilor.Models;

namespace Maetsilor.Controllers
{
    public class MembreController : Controller
    {
        private ApplicationDbContext _context = null;
        public MembreController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: Membre
        public ActionResult Index(string OrdreTri = null, string searchTerm = null, string searchField = null, int page = 1)
        {
            List<Membre> lmvm = new List<Membre>();
            foreach(ApplicationUser appUser in _context.Users)
            {
               lmvm.Add(new Membre(appUser));
            }

            if (HttpContext.Request.Headers["X-Requested-With"] == "XMLHttpRequest") //magie :)
                return PartialView("_IndexPartial", lmvm);
            else
                return View(lmvm);
        }

        // GET: Membre/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Membre/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Membre/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Membre/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Membre/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, IFormCollection collection)
        {
            try
            {

                ApplicationUser allo = _context.Users.Where(m => m.Id == id).Single();
               //No fucking clue. Sory
                

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Membre/Delete/5
        public ActionResult Delete(string id)
        {
            _context.Remove(_context.Users.Where(m => m.Id == id).Single());
            _context.SaveChanges();
            return RedirectToAction("Index");
            
        }

        // POST: Membre/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                return View();
            }
            catch
            {
                return View();
            }
        }
    }
}

src/Maetsilor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Maetsilor</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <style>
        body {
            background-color: #202020;
            color: #AAAAAA;
        }

        div.body-content {
            background-color: #282828;
        }

        #Logo {
            height: auto;
            max-width: 30%;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="img-responsive hidden-xs" asp-area="" asp-controller="Home" asp-action="Index">
                    <img id="Logo" src="~/images/LogoMaetsilor.png" alt="LogoMaetsilor" />
                </a>
            </div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Maetsilor</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">@Resource.Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">@Resource.About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    
                    @if (User.Identity.IsAuthenticated && !User.IsInRole("ExclusionForum"))
                    {
                        <li><a asp-area="" asp-controller="MatchMaking" asp-action="Index">@Resource.MatchMaking</a></li>
                        <li><a asp-area="" asp-controller="MatchMaking" asp-action="IndexUserGroups">@Resource.MyGroups</a></li>
                        <li><a asp-area="" asp-controller="Forum" asp-action="Index">Forum</a></li>
                    }
                    @if (User.IsInRole("Administrateur"))
                    {
                        <li><a asp-area="" asp-controller="Membre" asp-action="Index">@Resource.Members</a></li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <div class="row">
            <div class="col-md-6">
                <p>&copy; 2016 - Maetsilor</p>
            </div>
            <div class="col-md-6 text-right">
                @await Html.PartialAsync("_SelectLanguagePartial")
            </div>
        </div>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/Maetsilor/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
    .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
    .ToList();
}
<div title="@Localizer["Langue:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="Home" asp-action="SetLanguage" asp-routereturnUrl="@Context.Request.Path"
          method="post" class="form-horizontal" role="form">
        @Localizer["Langue:"]
        <select name="culture" asp-for="@requestCulture.RequestCulture.UICulture.Name"
                asp-items="cultureItems" onchange="this.form.submit()"></select>
    </form>
</div>